# hosts/cope/hardware-configuration.nix
#
# Auto-generated by nixos-generate-config. Lives outside modules/ because it
# is machine-specific boilerplate, not an authored feature.
# Imported directly in modules/nix/flake-parts/lib.nix via `self`.
#
# Replace this entire file with /etc/nixos/hardware-configuration.nix
# from your fresh NixOS install.
{ ... }: { }
